services:
  redis:
    image: redis:7.4.1-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    # volumes:
    # - redis_data:/data
    # command: redis-server --appendonly yes # only for prod
    command: ["redis-server", "--loglevel", "debug"]
    environment:
      - REDIS_PASSWORD=password
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_DB=0
      - REDIS_TLS_ENABLED=false
  database:
    image: mariadb:12.0.2
    restart: unless-stopped
    environment:
      - MYSQL_USER=user
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
