services:
  database:
    image: mariadb:12.0.2
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
    # ports:
    # - "3306:3306"
    volumes:
      - gofitshop_db_data:/var/lib/mysql
    networks:
      - gofitshop_network
  redis:
    image: redis:7.4.1-alpine
    restart: unless-stopped
    command: ["redis-server", "--loglevel", "warning"]
    volumes:
      - gofitshop_redis_data:/data
    networks:
      - gofitshop_network
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    volumes:
      - gofitshop_qdrant_data:/qdrant/storage
    networks:
      - gofitshop_network
  ollama:
    image: ollama/ollama:latest
    # ports:
    # - "11434:11434"
    restart: unless-stopped
    networks:
      - gofitshop_network
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull mistral:7b &&
      ollama pull qwen3-embedding:4b &&
      wait
      "
  api:
    build: .
    networks:
      - gofitshop_network
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - database
      - ollama
      - redis
      - qdrant
  nextjs:
    build: ../web
    restart: unless-stopped
    networks:
      - gofitshop_network
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - BACKEND_URL=http://api:8080

networks:
  gofitshop_network:
volumes:
  gofitshop_db_data:
  gofitshop_redis_data:
  gofitshop_qdrant_data:
