services:
  database:
    image: mariadb:12.0.2
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=password
    # ports:
    # - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gofitshop_network
  redis:
    image: redis:7.4.1-alpine
    restart: unless-stopped
    command: ["redis-server", "--loglevel", "warning"]
    volumes:
      - redis_data:/data
    networks:
      - gofitshop_network
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - gofitshop_network
  ollama:
    image: ollama/ollama:latest
    # ports:
    # - "11434:11434"
    restart: unless-stopped
    networks:
      - gofitshop_network
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 5 &&
      ollama pull mistral:7b &&
      ollama pull qwen3-embedding:4b &&
      wait
      "
  # api:
  #   build: ./api
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - database
  #     - ollama
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama:11434
  #     - OLLAMA_LLM_MODEL=mistral:7b
  #     - OLLAMA_EMBEDDING_MODEL=qwen3-embedding:4b

networks:
  gofitshop_network:
volumes:
  db_data:
  redis_data:
  qdrant_data:
