metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"
# metadata_auto_snapshot_interval = "6h"

# replication_factor = 3
replication_factor = 1

compression_level = 2

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "bd9ce2433e9404731cf3e337f453b2639fd25bd0aacdd31f5da1d49eb8f3c36f" # openssl rand -hex 32

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage"
index = "index.html"

[admin]
api_bind_addr="0.0.0.0:3903"
metrics_token="xRj0o2f1cdbGGv0TOhRqL8sN+aPiYpaaXgT4I0zunKE=" # openssl rand -base64 32
admin_token="i+6n3Ez7/FSbjMuDeMNy0niBxqY2pf2aDvTAc0kI4pU=" # openssl rand -base64 32


# docs: https://garagehq.deuxfleurs.fr/documentation/cookbook/real-world/#deploying-and-configuring-garage