schema {
  query: Query
  mutation: Mutation
}

enum AttributeKeySortingField {
  CREATED_AT
  ID
  KEY
  UPDATED_AT
}

type BestSellingCategory {
  category: Category!
  itemsSold: Int!
  totalRevenueInCents: Float!
}

type BestSellingProductVariant {
  productVariant: ProductVariant!
  quantitySold: Int!
}

type Cart {
  createdAt: DateTime!
  id: Int!
  items: [CartItem!]!
  updatedAt: DateTime!
  userId: Int!
}

type CartItem {
  cartId: Int!
  createdAt: DateTime!
  id: Int!
  productVariant: ProductVariant!
  productVariantId: Int!
  quantity: Int!
  updatedAt: DateTime!
}

type Category {
  categoryProductVariants(attributeFilters: [[String!]!], cursor: Int, includeSubcategories: Boolean, pageSize: Int = 10): PaginatedProductVariant!
  createdAt: DateTime!
  description: String!
  id: Int!
  isPublic: Boolean!
  isSetup: Boolean!
  name: String
  parentCategoryId: Int
  productsCount: Int!
  slug: String!
  subcategories: [Category!]!
  translations(
    """
    empty array - all translations will be returned, [...string] - only the translation matching the locales in array will be returned
    """
    locales: [String!]!
  ): [CategoryTranslation!]!
  updatedAt: DateTime!
  usedProductVariantAttributes: [ProductVariantAttribute!]!
}

type CategoryEdge {
  cursor: Int!
  node: Category!
}

type CategoryTranslation {
  categoryId: Int!
  description: String
  id: Int!
  locale: String!
  name: String!
}

input CreateCategoryInput {
  """Parent category id"""
  parentCategoryId: Int
  """Slug of the category"""
  slug: String!
}

input CreateCategoryTranslationInput {
  """category id"""
  categoryId: Int!
  """Category description"""
  description: String
  """Locale code"""
  localeCode: String!
  """Category name"""
  name: String!
}

input CreateLLMPromptInput {
  productId: Int
  prompt: String!
}

input CreateProductInput {
  """Parent category id"""
  categoryId: Int
  isPublic: Boolean!
  """Product slug"""
  slug: String!
}

input CreateProductReviewInput {
  comment: String
  lang: String!
  orderItemId: Int!
  rating: Int!
}

input CreateProductTranslationInput {
  """Product description"""
  description: String
  """Locale code"""
  localeCode: String!
  """Product markdown content"""
  markdownContent: String
  """Product name"""
  name: String!
}

input CreateProductVariantAttributeInput {
  """Attribute Key ID"""
  keyId: Int!
  """Attribute Value"""
  value: String!
}

input CreateProductVariantAttributeKeyInput {
  key: String!
}

input CreateProductVariantAttributeKeyTranslationInput {
  keyId: Int!
  keyTranslation: String!
  localeCode: String!
}

input CreateProductVariantAttributeTranslationInput {
  attributeId: Int!
  locale: String!
  valueTranslation: String!
}

input CreateProductVariantInput {
  """List of Product Variant Attribute IDs"""
  attributes: [Int!]!
  isPublic: Boolean!
  priceInCents: Int!
  productId: Int!
  """Stock keeping unit"""
  sku: String!
  stock: Int!
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

input EditCategoryTranslationInput {
  """category translation id"""
  categoryTranslationId: Int!
  """Category description"""
  description: String
  """Locale code"""
  localeCode: String!
  """Category name"""
  name: String!
}

input EditProductTranslationInput {
  """Product description"""
  description: String
  """Locale code"""
  localeCode: String!
  """Product markdown content"""
  markdownContent: String
  """Product name"""
  name: String!
  """product translation id"""
  productTranslationId: Int!
}

enum EmbeddingTaskType {
  PRODUCT
  PRODUCT_CONTENT
}

type LLMTask {
  date: DateTime!
  id: Int!
  prompt: String!
  response: UserPromptResponse
  status: LLMTaskStatus!
  userId: Int!
}

enum LLMTaskStatus {
  COMPLETED
  FAILED
  IN_PROGRESS
  PENDING
}

type Locale {
  """Locale code"""
  code: String!
  flag: String!
  """Native locale name"""
  name: String!
}

type Mutation {
  addItemToCart(productVariantId: Int!, quantity: Int!): Cart!
  admin_deleteProductReview(reviewId: Int!): Boolean!
  cancelOrder(id: Int!): Order!
  changePassword(currentPassword: String!, newPassword: String!): Void!
  createCategory(createCategoryInput: CreateCategoryInput!): Category!
  createCategoryTranslation(newTranslationinput: CreateCategoryTranslationInput!): CategoryTranslation!
  createLlmTask(input: CreateLLMPromptInput!): LLMTask!
  createProduct(createProductInput: CreateProductInput!): Product!
  createProductReview(input: CreateProductReviewInput!): ProductReview!
  createProductTranslation(createProductTranslationInput: CreateProductTranslationInput!, productId: Int!): ProductTranslation!
  createProductVariant(createProductVariantInput: CreateProductVariantInput!): ProductVariant!
  createProductVariantAttribute(createProductVariantAttributeInput: CreateProductVariantAttributeInput!): ProductVariantAttribute!
  createProductVariantAttributeKey(createProductVariantAttributeKeyInput: CreateProductVariantAttributeKeyInput!): ProductVariantAttributeKey!
  createProductVariantAttributeKeyTranslation(input: CreateProductVariantAttributeKeyTranslationInput!): ProductVariantAttributeKeyTranslation!
  createProductVariantAttributeTranslation(input: CreateProductVariantAttributeTranslationInput!): ProductVariantAttributeTranslation!
  deleteAccount: Void
  deleteAvatar: Void!
  deleteCategoryTranslation(categoryTranslationId: Int!): Int!
  deleteProductImage(productImageId: Int!): Int!
  deleteProductReview(reviewId: Int!): Boolean!
  deleteProductTranslation(productTranslationId: Int!): Int!
  editProductTranslation(editProductTranslationInput: EditProductTranslationInput!): ProductTranslation!
  generateProductContentEmbedding(lang: String!, productId: Int!): ProductEmbedding
  generateProductEmbedding(lang: String!, productId: Int!): ProductEmbedding
  logoutAll: Void!
  regenerateAllProductContentEmbeddings: Void!
  regenerateAllProductEmbeddings: Void!
  removeCategory(id: Int!): Category!
  removeProduct(id: Int!): Product!
  removeProductVariant(id: Int!): Int!
  removeProductVariantAttribute(id: Int!): Void!
  removeProductVariantAttributeKey(id: Int!): Void!
  removeProductVariantAttributeKeyTranslation(id: Int!): Void!
  removeProductVariantAttributeTranslation(id: Int!): Void!
  removeProductVariantImage(id: Int!): Int!
  retryPendingPayment(orderId: Int!): String!
  setProductThumbnailImage(productImageId: Int!): ProductImage!
  setProductVariantThumbnailImage(id: Int!): ProductVariantImage!
  updateCartItemQuantity(cartItemId: Int!, quantity: Int!): Cart!
  updateCategory(updateCategoryInput: UpdateCategoryInput!): Category!
  updateCategoryTranslation(editTranslationInput: EditCategoryTranslationInput!): CategoryTranslation!
  updateOrder(input: UpdateOrderDto!, orderId: Int!): Void!
  updatePassword(input: UpdatePasswordInput!): Void!
  updateProduct(updateProductInput: UpdateProductInput!): Product!
  updateProductReview(input: UpdateProductReviewInput!): ProductReview!
  updateProductVariant(updateProductVariantInput: UpdateProductVariantInput!): ProductVariant!
  updateProductVariantAttribute(updateProductVariantAttributeInput: UpdateProductVariantAttributeInput!): ProductVariantAttribute!
  updateProductVariantAttributeKey(updateProductVariantAttributeKeyInput: UpdateProductVariantAttributeKeyInput!): ProductVariantAttributeKey!
  updateProductVariantAttributeKeyTranslation(input: UpdateProductVariantAttributeKeyTranslationInput!): ProductVariantAttributeKeyTranslation!
  updateProductVariantAttributeTranslation(input: UpdateProductVariantAttributeTranslationInput!): ProductVariantAttributeTranslation!
  updateUser(input: UpdateUserInput!): User!
  updateUserRole(newRole: Role!, userId: Int!): Void!
}

type Order {
  createdAt: DateTime!
  id: Int!
  items: [OrderItem!]!
  shippingDetails: OrderShippingDetails
  status: OrderStatus!
  totalInCents: Int!
  updatedAt: DateTime!
  userId: Int
}

type OrderEdge {
  cursor: Int!
  node: Order!
}

type OrderItem {
  createdAt: DateTime!
  id: Int!
  orderId: Int!
  productReview: ProductReview
  productVariant: ProductVariant
  productVariantId: Int
  quantity: Int!
  sku: String!
  unitPriceInCents: Int!
  updatedAt: DateTime!
}

type OrderShippingDetails {
  city: String
  country: String!
  createdAt: DateTime!
  id: Int!
  line1: String!
  line2: String
  name: String!
  orderId: Int!
  phone: String
  postalCode: String!
  state: String
  updatedAt: DateTime!
}

enum OrderStatus {
  CANCELED
  DELIVERED
  FAILED
  PENDING
  PROCESSING
  SHIPPED
}

type OverallTrendStatistic {
  percentChange: Float!
  points: [RevenueDataPoint!]!
  timePeriod: TimePeriod!
}

type PaginatedCategory {
  edges: [CategoryEdge!]
  nextCursor: Int
  totalCount: Int!
}

type PaginatedOrder {
  edges: [OrderEdge!]
  nextCursor: Int
  totalCount: Int!
}

type PaginatedProduct {
  edges: [ProductEdge!]
  nextCursor: Int
  totalCount: Int!
}

type PaginatedProductReview {
  edges: [ProductReviewEdge!]
  nextCursor: Int
  totalCount: Int!
}

type PaginatedProductVariant {
  edges: [ProductVariantEdge!]
  nextCursor: Int
  totalCount: Int!
}

type PaginatedProductVariantAttributeKey {
  edges: [ProductVariantAttributeKeyEdge!]
  nextCursor: Int
  totalCount: Int!
}

type PaginatedUser {
  edges: [UserEdge!]
  nextCursor: Int
  totalCount: Int!
}

type Product {
  categoryId: Int
  contentEmbeddings: [ProductEmbedding!]!
  createdAt: DateTime!
  description: String
  embeddings: [ProductEmbedding!]!
  """Product ID"""
  id: Int!
  images: [ProductImage!]!
  isPublic: Boolean!
  isSetup: Boolean!
  markdownContent: String
  missingContentEmbeddingLanguages: [String!]!
  missingEmbeddingLanguages: [String!]!
  name: String
  """Product slug"""
  slug: String!
  thumbnailImage: ProductImage
  translations: [ProductTranslation!]!
  updatedAt: DateTime!
  variants(includeHidden: Boolean! = false): [ProductVariant!]!
}

type ProductEdge {
  cursor: Int!
  node: Product!
}

type ProductEmbedding {
  createdAt: DateTime!
  id: Int!
  lang: String!
  productId: Int!
  status: LLMTaskStatus!
  type: EmbeddingTaskType!
}

type ProductImage {
  id: Int!
  isThumbnail: Boolean!
  productId: Int!
  url: String!
}

type ProductReview {
  author: ProductReviewAuthor
  comment: String
  createdAt: DateTime!
  id: Int!
  lang: String!
  orderItemId: Int!
  productVariant: ProductVariant
  rating: Int!
}

type ProductReviewAuthor {
  avatarUrl: String
  firstName: String!
  lastName: String!
}

type ProductReviewEdge {
  cursor: Int!
  node: ProductReview!
}

type ProductTranslation {
  description: String
  id: Int!
  locale: String!
  markdownContent: String
  name: String!
  productId: Int!
}

type ProductVariant {
  attributes: [ProductVariantAttribute!]!
  createdAt: DateTime!
  id: Int!
  images: [ProductVariantImage!]!
  isPublic: Boolean!
  priceInCents: Int!
  product: Product!
  productId: Int!
  sku: String!
  stock: Int!
  thumbnailImage: ProductVariantImage
  updatedAt: DateTime!
}

type ProductVariantAttribute {
  attributeKeyId: Int!
  id: Int!
  key: ProductVariantAttributeKey
  productVariants: [ProductVariant!]!
  translatedValue: String
  translations: [ProductVariantAttributeTranslation!]!
  value: String!
}

type ProductVariantAttributeKey {
  attributes: [ProductVariantAttribute!]!
  createdAt: DateTime!
  id: Int!
  key: String!
  translatedKey: String
  translations: [ProductVariantAttributeKeyTranslation!]!
  updatedAt: DateTime!
}

type ProductVariantAttributeKeyEdge {
  cursor: Int!
  node: ProductVariantAttributeKey!
}

type ProductVariantAttributeKeyTranslation {
  attributeKeyId: Int!
  id: Int!
  keyTranslation: String!
  locale: String!
}

type ProductVariantAttributeTranslation {
  attributeId: Float!
  id: Float!
  locale: String!
  value: String!
}

type ProductVariantEdge {
  cursor: Int!
  node: ProductVariant!
}

type ProductVariantImage {
  id: Int!
  isThumbnail: Boolean!
  productVariantId: Int!
  url: String!
}

type Query {
  allProducts(
    """
    null - only products with no category will be returned, 0 - all products will be returned, int >= 1 - only the children of category with given id will be returned
    """
    categoryId: Int
    isPublic: Boolean
    isSetup: Boolean
    slug: String
  ): [Product!]!
  bestSellingCategoriesStatistic(limit: Int, timePeriod: TimePeriod!): [BestSellingCategory!]
  bestSellingProductVariantsStatistic(limit: Int, timePeriod: TimePeriod!): [BestSellingProductVariant!]
  cart: Cart!
  categories(
    """
    If true, sort in ascending order, else descending. If null, default sorting order is used
    """
    ascending: Boolean
    """Filter categories by id equal to this value"""
    idQuery: Int
    isPublic: Boolean
    isSetup: Boolean
    """
    null - only categories with no parent category will be returned, 0 - all categories will be returned, int >= 1 - only the children of category with given id will be returned
    """
    parentCategoryId: Int
    """Filter categories by slug containing this query string"""
    slugQuery: String
    """Field to sort by"""
    sortBy: String
  ): [Category!]!
  category(id: Int, isPublic: Boolean, isSetup: Boolean, slug: String): Category!
  findAllPaginatedOrders(ascending: Boolean, cursor: Int, dateFrom: DateTime, dateTo: DateTime, id: Int, maxPrice: Int, minPrice: Int, pageSize: Int = 10, sortBy: String, status: OrderStatus, userId: Int): PaginatedOrder!
  findAllPaginatedProductVariantAttributeKeys(ascending: Boolean, cursor: Int, id: Int, key: String, pageSize: Int = 10, sortBy: AttributeKeySortingField): PaginatedProductVariantAttributeKey!
  findAllPaginatedUsers(ascending: Boolean, cursor: Int, email: String, id: Int, pageSize: Int = 10, role: Role, sortBy: UserSortingField): PaginatedUser!
  findOneProductVariantAttribute(id: Int!): ProductVariantAttribute
  findOrderById(id: Int!): Order
  getUserLLMTaskById(id: Int!): LLMTask
  locale(id: String!): Locale!
  locales: [Locale!]!
  me: User!
  missingProductContentEmbeddingLanguages(productId: Int!): [String!]!
  missingProductEmbeddingLanguages(productId: Int!): [String!]!
  order(id: Int!): Order
  orders: [Order!]!
  paginatedCategories(
    """
    If true, sort in ascending order, else descending. If null, default sorting order is used
    """
    ascending: Boolean
    cursor: Int
    """Filter categories by id equal to this value"""
    idQuery: Int
    isPublic: Boolean
    isSetup: Boolean
    pageSize: Int = 10
    """
    null - only categories with no parent category will be returned, 0 - all categories will be returned, int >= 1 - only the children of category with given id will be returned
    """
    parentCategoryId: Int
    """Filter categories by slug containing this query string"""
    slugQuery: String
    """Field to sort by"""
    sortBy: String
  ): PaginatedCategory!
  paginatedProductReviews(cursor: Int, pageSize: Int = 10): PaginatedProductReview!
  paginatedProductReviewsByProductId(cursor: Int, pageSize: Int = 10, productId: Int!): PaginatedProductReview!
  product(id: Int!, isPublic: Boolean, isSetup: Boolean): Product
  productBySlug(slug: String!): Product
  productContentEmbedding(id: Int!): ProductEmbedding
  productContentEmbeddings(productId: Int!): [ProductEmbedding!]!
  productEmbedding(id: Int!): ProductEmbedding
  productEmbeddings(productId: Int!): [ProductEmbedding!]!
  productVariantAttributeKey(id: Int!): ProductVariantAttributeKey!
  productVariantAttributeKeys(productId: Int): [ProductVariantAttributeKey!]!
  productVariantAttributes: [ProductVariantAttribute!]!
  productVariantsByIds(ids: [Int!]!): [ProductVariant!]!
  products(
    ascending: Boolean
    """
    null - only products with no category will be returned, 0 - all products will be returned, int >= 1 - only the children of category with given id will be returned
    """
    categoryId: Int
    cursor: Int
    isPublic: Boolean
    isSetup: Boolean
    pageSize: Int = 10
    slug: String
    sortBy: String
  ): PaginatedProduct!
  revenuePerDayStatistic(timePeriod: TimePeriod!): OverallTrendStatistic
  searchProductVariants(ascending: Boolean, attributeFilters: [[String!]!], cursor: Int, pageSize: Int = 10, searchTerm: String, sortBy: String): PaginatedProductVariant!
  user(id: ID!): User!
}

type RevenueDataPoint {
  date: String!
  revenue: Float!
}

"""User role"""
enum Role {
  ADMIN
  USER
}

enum TimePeriod {
  LAST_NINETY_DAYS
  LAST_SEVEN_DAYS
  LAST_THIRTY_DAYS
}

input UpdateCategoryInput {
  """Category id"""
  id: Int!
  """Parent category id"""
  parentCategoryId: Int
  """Slug of the category"""
  slug: String!
}

input UpdateOrderDto {
  status: OrderStatus!
}

input UpdatePasswordInput {
  confirmNewPassword: String!
  currentPassword: String!
  newPassword: String!
}

input UpdateProductInput {
  """Parent category id"""
  categoryId: Int
  id: Int!
  isPublic: Boolean!
  """Product slug"""
  slug: String!
}

input UpdateProductReviewInput {
  comment: String
  id: Int!
  lang: String!
  rating: Int!
}

input UpdateProductVariantAttributeInput {
  id: Int!
  """Attribute Value"""
  value: String!
}

input UpdateProductVariantAttributeKeyInput {
  id: Int!
  key: String
}

input UpdateProductVariantAttributeKeyTranslationInput {
  id: Int!
  keyTranslation: String!
  localeCode: String!
}

input UpdateProductVariantAttributeTranslationInput {
  id: Int!
  locale: String!
  valueTranslation: String!
}

input UpdateProductVariantInput {
  """List of Product Variant Attribute IDs"""
  attributes: [Int!]
  id: Int!
  isPublic: Boolean
  priceInCents: Int
  productId: Int
  """Stock keeping unit"""
  sku: String
  stock: Int
}

input UpdateUserInput {
  email: String!
  lastName: String!
  name: String!
}

type User {
  avatarUrl: String
  createdAt: DateTime!
  email: String!
  firstName: String!
  id: Int!
  lastName: String
  orders: [Order!]!
  role: Role!
  updatedAt: DateTime!
}

type UserEdge {
  cursor: Int!
  node: User!
}

type UserPromptResponse {
  id: Int!
  products: [Product!]
  text: String!
}

enum UserSortingField {
  CREATED_AT
  EMAIL
  ID
  ROLE
  UPDATED_AT
}

"""Represents NULL values"""
scalar Void